//@version=6
indicator("CCI with Conditional Coloring", overlay=false)

// Inputs
sc = input.source(hlc3, 'source')
L1 = input.int(6, title='l1', minval=1, maxval=500, step=1, tooltip='length1', group='length')
L2 = input.int(14, title='l2', minval=1, maxval=500, step=1, tooltip='length2', group='length')
L3 = input.int(28, title='l3', minval=1, maxval=500, step=1, tooltip='length3', group='length')
L4 = input.int(56, title='l4', minval=1, maxval=500, step=1, tooltip='length4', group='length')

// CCI calculations
c1 = ta.cci(sc, L1)
c2 = ta.cci(sc, L2)
c3 = ta.cci(sc, L3)
c4 = ta.cci(sc, L4)

// Conditional color logic for c1
c1Color = c1 > 0 and c1 > c1[2] ? #45a9d4 : 
          c1 > 0 and c1 < c1[2] ? #455dd4af : 
          c1 < 0 and c1 < c1[2] ? #d445b9 : 
          c1 < 0 and c1 > c1[2] ? #d44577af : 
          color.gray

c2Color = c2 > 0 and c2 > c2[2] ? #1aa901 : 
          c2 > 0 and c2 < c2[2] ? #00620b : 
          c2 < 0 and c2 < c2[2] ? #50005c : 
          c2 < 0 and c2 > c2[2] ? #d445cdaf : 
          color.gray

c3Color = c3 > 0 and c3 > c3[2] ? #ffd500 : 
          c3 > 0 and c3 < c3[2] ? #d06f00 : 
          c3 < 0 and c3 < c3[2] ? #be1d1d : 
          c3 < 0 and c3 > c3[2] ? rgb(255, 0, 0)


c4Color = c4 > 0 and c4 > c4[2] ? #fafafa :
          c4 > 0 and c4 < c4[2] ? #666666 :
          c4 < 0 and c4 < c4[2] ? #000000 :
          c4 < 0 and c4 > c4[2] ? #444444 :
          color.gray

          // Plot c1 with conditional coloring
plot(c4,  title='CCI4 back',color= color.new(#000000,60), linewidth=6)
plot(c4,'cci4', color=c4Color, linewidth=2)

plot(c3,title='CCI3 back',color= color.new(#000000,60), linewidth=6)
plot(c3, 'cci3', color=c3Color, linewidth=2)

plot(c2, title='CCI2 back',color= color.new(#000000,60), linewidth=6)
plot(c2, 'cci2', color=c2Color, linewidth=2)

plot(c1, title='CCI1 back',color= color.new(#000000,60), linewidth=6)
plot(c1, 'cci1', color=c1Color, linewidth=2)



// Optional: Plot zero line for reference
plot(   0, "Zero Line", color.new(#884f88,0), linestyle=plot().linestyle_dotted)
plot( 100, "100 Line", color.new(#884f88,0), linestyle=plot().linestyle_dotted)
plot(-100, "-100 Line", color.new(#884f88,0), linestyle=plot().linestyle_dotted)
plot( 250, "250 Line", color.new(#884f88, 0), linestyle=plot.linestyle_dotted)
plot(-250, "-250 Line", color.new(#884f88, 0), linestyle=plot.linestyle_dotted)