//xanders Diversity Inclusion Community Kickback Rider wavetrend kumo+enhanced ++

// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © OskarGallard

//@version=6
indicator('WaveTrend Oscillator Plus', '𝗪𝗮𝘃𝗲𝗧𝗿𝗲𝗻𝗱 [+]', false)
// Tick Volume
tick = syminfo.mintick
rng = close - open
tickrng = tick
tickrng := math.abs(rng) < tick ? nz(tickrng[1]) : rng
tickvol = math.abs(tickrng) / tick
volumen = nz(volume) != 0 ? volume : tickvol

enhanced_vwma(_series, _length) =>    
    vmp = _series * volumen
    VWMA = math.sum(vmp, _length) / math.sum(volumen, _length)
    VWMA

// ALMA - Arnaud Legoux Moving Average of @kurtsmock
enhanced_alma(_series, _length, _offset, _sigma) =>
    length = int(_length) // Floating point protection
    numerator = 0.0
    denominator = 0.0
    m = _offset * (length - 1)
    s = length / _sigma
    for i = 0 to length - 1 by 1
        weight = math.exp(-((i - m) * (i - m)) / (2 * s * s))
        numerator := numerator + weight * _series[length - 1 - i]
        denominator := denominator + weight
        denominator
    numerator / denominator

//T3 Moving Average based on the article 'Smoothing Techniques For More Accurate Signals' by Tim Tillson
f_t3(src, len) =>
    x1 = ta.ema(src, len) //(hlcc, 8)
    x2 = ta.ema(x1, len)
    x3 = ta.ema(x2, len)
    x4 = ta.ema(x3, len)
    x5 = ta.ema(x4, len)
    x6 = ta.ema(x5, len)
    b = 0.7 //Volume Factor
    c1 = -math.pow(b, 3)
    c2 = 3 * math.pow(b, 2) + 3 * math.pow(b, 3)
    c3 = -6 * math.pow(b, 2) - 3 * b - 3 * math.pow(b, 3)
    c4 = 1 + 3 * b + math.pow(b, 3) + 3 * math.pow(b, 2)
    c1 * x6 + c2 * x5 + c3 * x4 + c4 * x3

// Kaufman's Adaptive Moving Average - Fast and Slow Ends
kama(x, t) =>
    fastK = 0.666 // KAMA Fast End
    slowK = 0.0645 // KAMA Slow End
    dist = math.abs(x[0] - x[1])
    signal_x = math.abs(x - x[t])
    noise = math.sum(dist, t)
    effr = noise != 0 ? signal_x / noise : 1
    sc = math.pow(effr * (fastK - slowK) + slowK, 2)
    KAma = x
    KAma := nz(KAma[1]) + sc * (x - nz(KAma[1]))
    KAma

// Jurik Moving Average of @everget
jma(src, length, power, phase) =>
    phaseRatio = phase < -100 ? 0.5 : phase > 100 ? 2.5 : phase / 100 + 1.5
    beta = 0.45 * (length - 1) / (0.45 * (length - 1) + 2)
    alpha = math.pow(beta, power)
    Jma = 0.0
    e0 = 0.0
    e0 := (1 - alpha) * src + alpha * nz(e0[1])
    e1 = 0.0
    e1 := (src - e0) * (1 - beta) + beta * nz(e1[1])
    e2 = 0.0
    e2 := (e0 + phaseRatio * e1 - nz(Jma[1])) * math.pow(1 - alpha, 2) + math.pow(alpha, 2) * nz(e2[1])
    Jma := e2 + nz(Jma[1])
    Jma

// VAMA - Volume Adjusted Moving Average of @allanster
vama(_src, _len, _fct, _rul, _nvb) => // vama(source,length,factor,rule,sample)
    tvb = 0 // total volume bars used in sample            
    tvb := _nvb == 0 ? nz(tvb[1]) + 1 : _nvb
    tvs = _nvb == 0 ? ta.cum(volumen) : math.sum(volumen, _nvb) // total volume in sample
    v2i = volumen / (tvs / tvb * _fct) // ratio of volume to increments of volume                                                  
    wtd = _src * v2i // weighted prices 
    nmb = 1 // initialize number of bars summed back               
    wtdSumB = 0.0 // initialize weighted prices summed back
    v2iSumB = 0.0 // initialize ratio of volume to increments of volume summed back
    for i = 1 to _len * 10 by 1 // set artificial cap for strict to VAMA length * 10 to help reduce edge case timeout errors
        strict = _rul ? false : i == _len // strict rule N bars' v2i ratios >= vama length, else <= vama length
        wtdSumB := wtdSumB + nz(wtd[i - 1]) // increment number of bars' weighted prices summed back
        v2iSumB := v2iSumB + nz(v2i[i - 1]) // increment number of bars' v2i's summed back
        if v2iSumB >= _len or strict // if chosen rule met
            break // break (exit loop)
        nmb := nmb + 1 // increment number of bars summed back counter
        nmb
    //nmb         // number of bars summed back to fulfill volume requirements or vama length
    //wtdSumB     // number of bars' weighted prices summed back
    //v2iSumB     // number of bars' v2i's summed back
    vama = (wtdSumB - (v2iSumB - _len) * _src[nmb]) / _len // volume adjusted moving average
    vama

// Variable Index Dynamic Average (VIDYA) by Tushar Chande
VIDYA(src, length) =>
    valpha = 2 / (length + 1)
    vud1 = src > src[1] ? src - src[1] : 0
    vdd1 = src < src[1] ? src[1] - src : 0
    vUD = math.sum(vud1, 9)
    vDD = math.sum(vdd1, 9)
    vCMO = nz((vUD - vDD) / (vUD + vDD))
    VAR = 0.0
    VAR := nz(valpha * math.abs(vCMO) * src) + (1 - valpha * math.abs(vCMO)) * nz(VAR[1])
    VAR

// https://www.tradingview.com/script/X67OSwqc-TASC-2024-04-The-Ultimate-Smoother/
// @function      The UltimateSmoother is a filter created
//                by subtracting the response of a high-pass 
//                filter from that of an all-pass filter.
// @param src     Source series.
// @param period  Critical period.
// @returns       Smoothed series.
UltimateSmoother(float src, int period) =>
    float a1 = math.exp(-1.414 * math.pi / period)
    float c2 = 2.0 * a1 * math.cos(1.414 * math.pi / period)
    float c3 = -a1 * a1
    float c1 = (1.0 + c2 - c3) / 4.0
    float us = src
    if bar_index >= 4
        us := (1.0 - c1) * src + (2.0 * c1 - c2) * src[1] - (c1 + c3) * src[2] + c2 * nz(us[1]) + c3 * nz(us[2])
        us
    us

ma(_type, _source, _length) =>
    switch _type
        'SMA' => ta.sma(_source, _length)
        'EMA' => ta.ema(_source, _length)
        'WMA' => ta.wma(_source, _length)
        'D_WMA' => ta.wma(ta.wma(_source, _length), _length) // Double Weighted Moving Average
        'D_EMA' => ta.ema(ta.ema(_source, _length), _length)
        'D_SMA' => ta.sma(ta.sma(_source, _length), _length)
        'VWMA' => enhanced_vwma(_source, _length)
        'D_VWMA' => enhanced_vwma(enhanced_vwma(_source, _length), _length)
        'ALMA' => enhanced_alma(_source, _length, 0.85, 6)
        'Wilder' => 
    	    wild = _source // Wilder's moving average
    	    wild := nz(wild[1]) + (_source - nz(wild[1])) / _length
    	    wild
        'T3' => f_t3(_source, _length)
        'HMA' => ta.hma(_source, _length)
        'VAMA' => vama(_source, _length, 0.67, true, 0)
        'KAMA' => kama(_source, _length)
        'JMA' => jma(_source, _length, 2, 50)
        'Ultimate Smoother' => UltimateSmoother(_source, _length)
        'D_T3' => f_t3(f_t3(_source, _length), _length)
        'Smooth LSMA' => 
    	    lsma = ta.linreg(_source, _length, 0)
    	    slsma = lsma - (lsma - ta.linreg(lsma, _length, 0))
    	    slsma
        'VIDYA' => VIDYA(_source, _length)
        'WMA(EMA)' => ta.wma(ta.ema(_source, _length), _length)

type bar
	float o = open
	float h = high
	float l = low
	float c = close

type osc
	float o = na
	float s = na
	float h = na

type alerts
	bool s = false
	bool b = false
	bool u = false
	bool d = false
	bool x = false
	bool y = false

type prompt
	string s = ''
	bool c = false

method notify(prompt p) =>
    if p.c
        alert(p.s, alert.freq_once_per_bar_close)

method any(alerts a) =>
    string s = switch 
        a.s => 'OS Signal'
        a.b => 'OB Signal'
        a.u => 'Bullish Trend'
        a.d => 'Bearish Trend'
        a.x => 'Bullish Swing'
        a.y => 'Bearish Swing'

        => na

    prompt.new(s, not na(s))

method src(bar b, simple string src) =>
    float x = switch src
        'open' => b.o
        'high' => b.h
        'low' => b.l
        'close' => b.c
        'oc2' => math.avg(b.o, b.c)
        'hl2' => math.avg(b.h, b.l)
        'hlc3' => math.avg(b.h, b.l, b.c)
        'ohl3' => math.avg(b.o, b.h, b.l)
        'och3' => math.avg(b.o, b.c, b.h) 
        'ocl3' => math.avg(b.o, b.c, b.l) 
        'ohlc4' => math.avg(b.o, b.h, b.l, b.c)
        'hlcc4' => math.avg(b.h, b.l, b.c, b.c)
        'vwap(Close)' => ta.vwap(b.c)
        'vwap(Open)' => ta.vwap(b.o)
        'vwap(High)' => ta.vwap(b.h)
        'vwap(Low)' => ta.vwap(b.l)
    x

method stdev(float src, simple int len) =>
    float sq = 0.
    float psq = 0.
    float sum = 0.

    for k = 0 to len - 1 by 1
        val = nz(src[k])
        psq := sq
        sq := sq + (val - sq) / (1 + k)
        sum := sum + (val - sq) * (val - psq)
        sum

    math.sqrt(sum / (len - 1))

method wave(bar b, simple string src, simple int clen, simple int alen, simple int slen, string _type) =>
    float x = b.src(src)
    float m = ma(_type, x, clen) //ta.ema(x, clen)
    float d = x.stdev(clen)
    float o = ma(_type, (x - m) / d * 100, alen) //ta.ema((x - m) / d * 100, alen)
    float s = ta.sma(o, slen)

    osc.new(o, s, o - s)

f_getWT(fuente, clen, alen, slen) =>
    esa = ta.ema(hlc3, clen)
    dev_st = stdev(hlc3, clen)
    com = (hlc3 - esa) / dev_st * 100
    wt1 = ta.ema(com, alen)
    wt2 = ta.sma(wt1, slen)
    [wt1, wt2]

// Indicators activation section
show_WT = input.bool(true, '↪ Show WaveTrend ↩  ', inline = 'w0')
midL = input.bool(true, '▶ Show Midline', inline = 'w0')
show_black = input.bool(false, 'Use Black Background', inline = 'w0')
revb = input.bool(true, '', inline = 'reve')
revt = input.int(100, '》Reversion Threshold [75, 125]', 75, 125, inline = 'reve')
char_dn = input.string('💀', 'Overbought Symbol', inline = 'reve2')
char_up = input.string('🚀', 'Oversold Symbol', inline = 'reve2')
colb = input.string('Extremities', '》Background Color', ['None', 'Midline Cross', 'Extremities', 'Reversions', 'Slope'], inline = 'reve3')
show_cross = input.bool(false, 'Show The Crossings', inline = 'reve3')
compare = input.bool(false, 'Compare with Symbol', inline = 'CPR')
compare_symbol = input.symbol('CME_MINI:ES1!', '', inline = 'CPR')
//extSrc = request.security(compare_symbol, timeframe.period, hlc3, barmerge.gaps_off, barmerge.lookahead_on)

// show_EWO = input.bool(false, '↪ Show EWO ↩  ', inline = '0_ewo')
// show_bands = input.bool(true, 'Use Breaking Bands', inline = '0_ewo')
// show_signal = input.bool(false, 'Use Signal Line', inline = '0_ewo')
candles_XTL = input.bool(false, '↪ The Expert Trend Locator [Bars Color] ↩ ')




// Inputs : WaveTrend Oscillator {
const string gw = '⎆⎆⎆ WaveTrend Oscillator'
type_wt = input.string('EMA', 'Type', inline = 'w1', group = gw, options = ['Ultimate Smoother', 'Smooth LSMA', 'ALMA', 'T3', 'WMA(EMA)', 'WMA', 'EMA', 'SMA', 'Wilder', 'D_WMA', 'D_SMA', 'D_EMA', 'D_T3', 'VWMA', 'D_VWMA', 'HMA', 'JMA', 'VAMA', 'KAMA', 'VIDYA'])
src = input.string('hlc3', 'Source', inline = 'w1', group = gw , options = ['open', 'high', 'low', 'close', 'oc2', 'hl2', 'hlc3', 'ohlc4', 'hlcc4', 'vwap(Close)', 'vwap(Open)', 'vwap(High)', 'vwap(Low)'])
clen = input.int(10, 'Channel Length', 3, 55, 1, inline = 'w2', group = gw)
alen = input.int(21, 'Average Length', 3, 55, 1, inline = 'w2', group = gw)
slen = input.int(4, 'Signal  Length', 2, 20, 1, inline = 'w3', group = gw)



// WaveTrend Oscillator {
// Based on "WaveTrend Oscillator" - Author: @LazyBear - Modified by @EliCobra, @dgtrd and @OskarGallard
// https://www.tradingview.com/script/2KE8wTuF-Indicator-WaveTrend-Oscillator-WT/
// https://www.tradingview.com/script/9GmOkVyH-Enhanced-WaveTrend-Oscillator/
// https://www.tradingview.com/script/cYG1lqRI-WaveTrend-LazyBear-vX-by-DGT/
bar b = bar.new()
osc wt = b.wave(src, clen, alen, slen, type_wt)
[wt1x, wt2x] = f_getWT(src, clen, alen, slen)

const color colup = #00FFFF
const color coldn = #FF055D
const color colhu = #8080FF
const color colhd = #FF8080
const color colnt = #EFEFBF

color color_wt = wt.o > wt.s ? colup : coldn
color color_wtx = wt1x > wt2x ? #00FF6B : #FE5200
color color_wtx2 = wt1x > wt2x ? #00682C : #822A00
color colof = wt.o > wt.s ? color.new(colup, 50) : color.new(coldn, 50)
field_0 = wt.h
field_1 = wt.h
color colh = wt.h > 0 ? wt.h > field_0[1] ? color.new(colhu, 40) : color.new(colhu, 60) : wt.h < field_1[1] ? color.new(colhd, 40) : color.new(colhd, 60)

hline(midL ? 0 : na, 'Mid Line', color.new(colnt, 50), hline.style_dotted)
max = hline(show_WT ? +150 : na, display = display.none)
hh = hline(show_WT ? +125 : na, display = display.none)
lh = hline(show_WT ? +100 : na, display = display.none)
min = hline(show_WT ? -150 : na, display = display.none)
ll = hline(show_WT ? -125 : na, display = display.none)
hl = hline(show_WT ? -100 : na, display = display.none)
h = plot(show_WT ? wt.h * 2 : na, 'WT Histogram', colh, 1, plot.style_columns)
w = plot(show_WT ? wt.o : na, 'WaveTrend', color_wt, 1, plot.style_line)
s = plot(show_WT ? wt.s : na, 'Signal', display = display.none)
char_cross = '⦿'
wt_cross = ta.cross(wt.o, wt.s)
plotchar(show_cross and wt_cross ? wt.s : na, 'Crossing in the WT', char_cross, location.absolute, color_wt, size = size.tiny)

plot(compare ? wt1x : na, 'WaveTrend 2', color_wtx, 1, plot.style_line)
plot(compare ? wt2x : na, 'Signal(WaveTrend 2)', color_wtx2, 1, plot.style_circles)



fill(lh, hh, color.new(colhd, 86))
fill(hh, max, color.new(colhd, 79))
fill(ll, hl, color.new(colhu, 87))
fill(ll, min, color.new(colhu, 80))
fill(w, s, colof)

alerts a = alerts.new(ta.crossover(wt.o, wt.s) and wt.o < -revt, ta.crossunder(wt.o, wt.s) and wt.o > revt, ta.crossover(wt.o, 0), ta.crossunder(wt.o, 0), ta.crossover(wt.o, wt.s), ta.crossunder(wt.o, wt.s))

alertcondition(a.b, 'Overbought', 'WaveTrend : OB Signal')
alertcondition(a.s, 'Oversold  ', 'WaveTrend : OS Signal')
alertcondition(a.u, 'Midline Crossover ', 'WaveTrend : Bullish Trend')
alertcondition(a.d, 'Midline Crossunder', 'WaveTrend : Bearish Trend')
alertcondition(a.x, 'Oscillator Up', 'WaveTrend : Bullish Swing')
alertcondition(a.y, 'Oscillator Down', 'WaveTrend : Bearish Swing')

a.any().notify()

bgcolor(show_black ? color.new(#000000, 25) : na, title = 'Black background')
color col = switch colb
    'Midline Cross' => wt.o > 0 ? color.new(colup, 90) : color.new(coldn, 90)
    'Extremities' => wt.o > revt ? color.new(colup, 80) : wt.o < -revt ? color.new(coldn, 80) : na
    'Reversions' => a.b ? color.new(coldn, 70) : a.s ? color.new(colup, 70) : na
    'Slope' => wt.o > wt.s ? color.new(colup, 90) : color.new(coldn, 90)
    'None' => na
bgcolor(col)
// }




// Inputs : The Expert Trend Locator - XTL {
const string g_xtl = '⎆⎆⎆ Expert Trend Locator [XTL]'
period_xtl = input.int(26, 'Length', minval = 2, inline = 'xtl', group = g_xtl)
MA_Type2 = input.string('D_VWMA', 'Type', inline = 'xtl', group = g_xtl, options = ['Ultimate Smoother', 'Smooth LSMA', 'T3', 'D_T3', 'WMA(EMA)', 'SMA', 'EMA', 'WMA', 'D_WMA', 'VWMA', 'ALMA', 'Wilder', 'D_SMA', 'D_EMA', 'D_VWMA', 'HMA', 'VIDYA'])
src_xtl = input.string('hlc3', 'Source', inline = 'xtl', group = g_xtl, options = ['open', 'high', 'low', 'close', 'oc2', 'hl2', 'hlc3', 'ohlc4', 'hlcc4', 'vwap(Close)', 'vwap(Open)', 'vwap(High)', 'vwap(Low)'])
fixed_Value = input.int(37, 'Threshold Level', minval = 10, group = g_xtl, inline = 'xtl2')
uTrad = input.bool(false, 'Use the traditional CCI formula', group = g_xtl, inline = 'xtl2')
detect_bull = input.bool(false, '◁ Alert: Bullish Trend', inline = 'alert_xtl', group = g_xtl)
detect_bear = input.bool(false, '◁ Alert: Bearish Trend', inline = 'alert_xtl', group = g_xtl)
// }



// The Expert Trend Locator - XTL {
// Based on "Double CCI" || https://www.tradingview.com/script/4vIRtqeP/
media = ma(MA_Type2, b.src(src_xtl), period_xtl)
cciNT = (b.src(src_xtl) - media) / (0.015 * ta.dev(b.src(src_xtl), period_xtl))
cciT = (b.src(src_xtl) - media) / (0.015 * ta.dev(math.abs(b.src(src_xtl) - media), period_xtl))
values = uTrad ? cciT : cciNT

var color color_XTL = na
if values < -fixed_Value
    color_XTL := #EDA43D //#FF4000 // Bear
    color_XTL
if -fixed_Value <= values and values <= fixed_Value
    color_XTL := #EFEFBF // Neutral
    color_XTL
if values > fixed_Value
    color_XTL := #3D86ED //#00BFFF // Bull
    color_XTL

xtl_crossover = ta.crossover(values, fixed_Value)
xtl_crossunder = ta.crossunder(values, -fixed_Value)
cond_bull_xtl = detect_bull and xtl_crossover
cond_bear_xtl = detect_bear and xtl_crossunder

if cond_bull_xtl
    alert('Symbol = (' + syminfo.tickerid + ') \n TimeFrame = (' + timeframe.period + ') \n Current Price (' + str.tostring(close) + ') \n Bullish Trend [XTL].', alert.freq_once_per_bar_close)
if cond_bear_xtl
    alert('Symbol = (' + syminfo.tickerid + ') \n TimeFrame = (' + timeframe.period + ') \n Current Price (' + str.tostring(close) + ') \n Bearish Trend [XTL].', alert.freq_once_per_bar_close)

barcolor(candles_XTL ? color_XTL : na, title = 'XLT barcolor')




// Load Pivots
f_checkPivArrays(array<float> PriceArr, array<float> OscArr, array<int> BarsArr) =>
    if array.size(PriceArr) != array.size(OscArr) or array.size(PriceArr) != array.size(BarsArr) or array.size(OscArr) != array.size(BarsArr)
        runtime.error('Array sizes are not equal!')

f_loadNewPivValues(array<float> PriceArr, Price, array<float> OscArr, Osc, array<int> BarsArr, Bars) =>
    f_checkPivArrays(PriceArr, OscArr, BarsArr)
    array.unshift(PriceArr, Price)
    array.unshift(OscArr, Osc)
    array.unshift(BarsArr, Bars)


//Signal - Enhanced WaveTrend Oscillator {
plotchar(revb and a.b, 'Overbought Signal', char_dn, location.top, coldn, size = size.tiny)
plotchar(revb and a.s, 'Oversold Signal', char_up, location.bottom, colup, size = size.tiny)
// }



pivR = input(title = 'WT Pivot Lookback Right', defval = 1)
pivL = input(title = 'WT Pivot Lookback Left', defval = 20)
trshold = input(25, 'Pivot Threshold')


// Compute VPT ocillator

// // //Ichimoku
Tenkansen = (ta.highest(high, 9) + ta.lowest(low, 9)) / 2
Kijunsen = (ta.highest(high, 26) + ta.lowest(low, 26)) / 2
FutureSpanA = (Tenkansen + Kijunsen) / 2
FutureSpanB = (ta.highest(high, 52) + ta.lowest(low, 52)) / 2

//Implied volatility based on Kumo thickness
Kumodepth = math.abs(FutureSpanA - FutureSpanB)

//Normalize implied volatility
Indicator = Kumodepth
AverageIndicator = ta.sma(Indicator, 200)
StandardDeviation = ta.stdev(Indicator, 200)
UpperBand = AverageIndicator + 2 * StandardDeviation
LowerBand = AverageIndicator - 2 * StandardDeviation
NormalizedIndicator = (Indicator - LowerBand) / (UpperBand - LowerBand) * 100





//HMA 

lengthHMA = input.int(100, minval = 1, title = 'Hull Long Moving Averge')
srcHMA = input(close, title = 'Hull Moving Long Averge Source')
hullma = ta.wma(2 * ta.wma(srcHMA, lengthHMA / 2) - ta.wma(srcHMA, lengthHMA), math.floor(math.sqrt(lengthHMA)))

lengthHMA2 = input.int(30, minval = 1, title = 'Hull Short Moving Averge')
srcHMA2 = input(close, title = 'Hull Moving Short Averge Source')
hullma2 = ta.wma(2 * ta.wma(srcHMA2, lengthHMA2 / 2) - ta.wma(srcHMA2, lengthHMA2), math.floor(math.sqrt(lengthHMA2)))

//MFI 

lengthMFI = input.int(title = 'Money Flow Index Length', defval = 14, minval = 1, maxval = 2000)
srcMFI = hlc3
mfMFI = ta.mfi(srcMFI, lengthMFI)




perccolorMFI = mfMFI > 80 ? color.new(color.red, 50) : mfMFI < 20 ? color.new(color.green, 50) : mfMFI > 50 ? color.new(color.aqua, 50) : color.new(color.orange, 50)
pertextMFI = mfMFI > 80 ? 'MoneyFlow Overbought' : mfMFI < 20 ? 'MoneyFlow Oversold' : 'Money Flow'

hullhull = hullma - hullma2