import os
import datetime
import sys

# Define file paths (using the combined documents generated by compile_docs.py)
DOCS_DIR = r"d:\Cro\pinescript section\Official Pinescript docs"
USER_MANUAL_PATH = os.path.join(DOCS_DIR, "pinescript_v6_user_manual_combined.md")
REF_MANUAL_PATH = os.path.join(DOCS_DIR, "pinescript_v6_reference_manual_combined.md")

# Load compiled manual files
def load_docs():
    if not os.path.exists(USER_MANUAL_PATH) or not os.path.exists(REF_MANUAL_PATH):
        print("Error: Combined manual files not found. Please run 'compile_docs.py' first.")
        sys.exit(1)
        
    print("Loading combined user manual...")
    with open(USER_MANUAL_PATH, "r", encoding="utf-8") as f:
        user_manual = f.read()
        
    print("Loading combined reference manual...")
    with open(REF_MANUAL_PATH, "r", encoding="utf-8") as f:
        ref_manual = f.read()
        
    return user_manual, ref_manual

# =====================================================================
# METHOD 1: Using Google AI Studio (google-generativeai SDK)
# =====================================================================
def upload_to_ai_studio(api_key):
    try:
        import google.generativeai as genai
        from google.generativeai import caching
    except ImportError:
        print("Installing google-generativeai...")
        # Note: In real setup, run 'pip install google-generativeai'
        print("Please run 'pip install google-generativeai' first.")
        return

    genai.configure(api_key=api_key)
    
    user_manual, ref_manual = load_docs()
    full_text = f"{user_manual}\n\n=========================================\n\n{ref_manual}"
    
    print("\nCreating Context Cache in Gemini AI Studio...")
    # Cache expires in 3 days (can be updated / refreshed)
    ttl = datetime.timedelta(days=3)
    
    cache = caching.CachedContent.create(
        model='models/gemini-1.5-pro-002', # Or gemini-2.0-flash-exp / gemini-2.5-pro
        display_name='pinescript_v6_manuals',
        contents=[full_text],
        ttl=ttl,
    )
    
    print(f"✅ Cache Created Successfully!")
    print(f"   Name (ID): {cache.name}")
    print(f"   Model: {cache.model}")
    print(f"   Expires At: {cache.expire_time}")
    
    print("\nTesting Query against the Cache...")
    model = genai.GenerativeModel(model_name='models/gemini-1.5-pro-002')
    response = model.generate_content(
        "Based on the official v6 manual, what are the key differences in strategy.entry vs v5?",
        cached_content=cache
    )
    print("\nGemini Response:")
    print(response.text)

# =====================================================================
# METHOD 2: Using GCP Vertex AI (google-cloud-aiplatform SDK)
# =====================================================================
def upload_to_vertex_ai(project_id, location="us-central1"):
    try:
        import vertexai
        from vertexai.generative_models import GenerativeModel, Part
        from vertexai.preview.generative_models import caching
    except ImportError:
        print("Installing google-cloud-aiplatform...")
        print("Please run 'pip install google-cloud-aiplatform' first.")
        return

    vertexai.init(project=project_id, location=location)
    
    user_manual, ref_manual = load_docs()
    
    print(f"\nCreating Context Cache in GCP Vertex AI (Project: {project_id})...")
    # Cache duration (e.g., 7 days)
    ttl = datetime.timedelta(days=7)
    
    cached_content = caching.CachedContent.create(
        model_name="gemini-1.5-pro-002",
        display_name="pinescript_v6_docs_cache",
        contents=[
            Part.from_text(user_manual),
            Part.from_text(ref_manual)
        ],
        ttl=ttl,
    )
    
    print(f"✅ GCP Vertex AI Cache Created Successfully!")
    print(f"   Resource Name: {cached_content.resource_name}")
    print(f"   Expires At: {cached_content.expire_time}")
    
    print("\nQuery Example:")
    print(f"To query this cache in Python:")
    print(f"    from vertexai.generative_models import GenerativeModel")
    print(f"    model = GenerativeModel(model_name='gemini-1.5-pro-002', cached_content='{cached_content.resource_name}')")
    print(f"    response = model.generate_content('Write a crossover strategy using ta.ema')")

if __name__ == "__main__":
    print("Pine Script v6 GCP Context Cache Uploader")
    print("----------------------------------------")
    print("This script helps you create a cached Gemini prompt containing your 1.25M token manual.")
    print("To use this, configure your billing/API keys and run the appropriate method.")
    
    # Example instructions
    print("\nHow to run:")
    print("1. Set your environment API key or project ID.")
    print("2. Call upload_to_ai_studio(YOUR_API_KEY) or upload_to_vertex_ai(YOUR_PROJECT_ID).")
