// //@version=5
// indicator("Linefill Between Lines", overlay = true)

// // Create two lines
// var line1 = line.new(bar_index - 10, high, bar_index, high, color=color.red, width=2)
// var line2 = line.new(bar_index - 10, low, bar_index, low, color=color.green, width=2)

// // Fill the area between them
// if barstate.islast
//     line.set_x2(line1, bar_index)
//     line.set_x2(line2, bar_index)
//     linefill.new(line1, line2, color.new(color.purple, 80))


// //@version=5
// indicator("Gann Fan", overlay = true, max_bars_back = 400)
// // get colors into the array
// var color [] colors = array.from(
//  input(defval = color.red, title = "1/2", inline = "c1", group = "colors"),
//  input(defval = color.green, title = "1/3", inline = "c1", group = "colors"),
//  input(defval = #0097a7, title = "1/", inline = "c1", group = "colors"),
//  input(defval = color.olive, title = "1/8", inline = "c1", group = "colors"),
//  input(defval = color.teal, title = "2/1", inline = "c2", group = "colors"),
//  input(defval = #9598a1, title = "3/1", inline = "c2", group = "colors"),
//  input(defval = color.yellow, title = "4/1", inline = "c2", group = "colors"),
//  input(defval = #a5d6a7, title = "8/1", inline = "c2", group = "colors"),
//  input(defval = color.blue, title = "1/1", inline = "c3", group = "colors"))
// //Transparency or the bg colors
// transp = input.int(defval = 80, title = "Transparency", minval = 0, maxval = 100, tooltip = "Possible values are from 0 (not transparent) to 100 (invisible)")
// // labels
// showlabels = input.bool(defval = true, title = "Labels", inline = "labels")
// labelloc = input.int(defval = 50, title = "|  Label location", minval = 1, maxval = 300, inline = "labels")
// lstyle1i = input.string(defval = 'Solid', title = "Line Style", options = ['Solid', 'Dashed', 'Dotted'], inline = "lstyle")
// lstyle2i = input.string(defval = 'Dashed', title = "", options = ['Solid', 'Dashed', 'Dotted'], inline = "lstyle")
// loopbackprd = input.int(defval = 280, title = "Loopback Period", tooltip = "Loopback period to search Highest/Lowest Pivot Points")
// pperiod = input.int(defval = 5, title = "Pivot Period")

// // calculate middle line, using this line we will calculate other lines
// float l_ = ta.lowest(292)
// float h_ = ta.highest(292)
// float perc = (h_ - l_) /82
// float hh = h_ + perc * 10
// float ll = l_ - perc * 8
// float middle = (hh - ll) / 131.0
// var lstyle1 = lstyle1i == 'Solid' ? line.style_solid : lstyle1i == 'Dashed' ? line.style_dashed : line.style_dotted
// var lstyle2 = lstyle2i == 'Solid' ? line.style_solid : lstyle2i == 'Dashed' ? line.style_dashed : line.style_dotted
// // levels
// var divs = array.from(2.0, 3.0, 4.0, 8.0)

// // remove old pivot points
// remove_old_pivots(pval, ploc)=>
//     for x = array.size(ploc) - 1 to 0
//         if bar_index - array.get(ploc, x) > loopbackprd
//             array.pop(ploc)
//             array.pop(pval)
            
// // get highest/lowest locations
// var pivothighs = array.new_float(0, na)
// var pivothighsloc = array.new_int(0, na)
// var pivotlows = array.new_float(0, na)
// var pivotlowsloc = array.new_int(0, na)
// ph = ta.pivothigh(pperiod, pperiod)
// pl = ta.pivotlow(pperiod, pperiod)
// if ph
//     array.unshift(pivothighsloc, bar_index - pperiod)
//     array.unshift(pivothighs, ph)
//     remove_old_pivots(pivothighs, pivothighsloc)
// if pl
//     array.unshift(pivotlowsloc, bar_index - pperiod)
//     array.unshift(pivotlows, pl)
//     remove_old_pivots(pivotlows, pivotlowsloc)

// l_bar_index = array.size(pivotlowsloc) > 0 ? array.get(pivotlowsloc, array.lastindexof(pivotlows, array.min(pivotlows))) : na
// h_bar_index = array.size(pivothighsloc) > 0 ? array.get(pivothighsloc, array.lastindexof(pivothighs, array.max(pivothighs))) : na
// lwest = low[bar_index - l_bar_index]
// hghest = high[bar_index - h_bar_index]

// // get line style
// get_style(x)=>
//     x == 1 ? l_bar_index <= h_bar_index ? lstyle1 : lstyle2 : l_bar_index > h_bar_index ? lstyle1 : lstyle2

// // remove old lines/labels/linefills
// remove_old_lll(lines, labels, linefills)=>
//     for x = 0 to array.size(lines) - 1
//         line.delete(array.get(lines, x))
//     for x = 0 to array.size(labels) - 1
//         label.delete(array.get(labels, x))
//     for x = 0 to array.size(linefills) - 1
//         linefill.delete(array.get(linefills, x))

// // get bar_index using y location and start point
// line_get_bar_index(gline, x_bar_index, yloc, mult)=>
//     ystart = line.get_price(gline, x_bar_index)
//     slope = math.abs(ystart - line.get_price(gline, x_bar_index + 1))
//     int ret = x_bar_index + math.floor((yloc - ystart) / slope) * mult

// // draw fan lines from lowest
// if l_bar_index > 0 and l_bar_index < bar_index
//     var uplines = array.new_line(9, na)
//     var ulinefill = array.new_linefill(8, na)
//     var labels = array.new_label(9, na)
//     remove_old_lll(uplines, labels, ulinefill)
    
//     // draw 1/1 line, show its label and keep its y level
//     array.set(uplines, 0, line.new(x1 = l_bar_index, y1 = lwest, x2 = l_bar_index + 1, y2 = lwest + middle, extend = extend.right, color = array.get(colors, 8), style = get_style(1)))
//     xloc = l_bar_index + labelloc
//     yloc11 = line.get_price(array.get(uplines, 0), xloc)
//     if showlabels
//         array.set(labels, 0, label.new(x = xloc, y = yloc11, text = "1/1", textcolor = array.get(colors, 8), style = label.style_none))
    
//     // draw other fan lines, labels, linefills 
//     for x = 0 to 3
//         array.set(uplines, x + 1, line.new(x1 = l_bar_index, y1 = lwest, x2 = bar_index, y2 = lwest + (line.get_price(array.get(uplines, 0), bar_index) - lwest) / array.get(divs,x), 
//                                            extend = extend.right, 
//                                            color = array.get(colors, x), 
//                                            style = get_style(1)))
//         array.set(ulinefill, x, linefill.new(array.get(uplines, x + 1), array.get(uplines, x), color.new(array.get(colors, x), transp)))
//         if showlabels
//             yloc = line.get_price(array.get(uplines, x + 1), xloc)
//             array.set(labels, x + 1, label.new(x = xloc, y = yloc, text = "1/" + str.tostring(array.get(divs, x)), textcolor = array.get(colors, x), style = label.style_none))
        
//         array.set(uplines, x + 5, line.new(x1 = l_bar_index, y1 = lwest, x2 = l_bar_index + 1, y2 = lwest + middle * array.get(divs,x), 
//                                            extend = extend.right, 
//                                            color = array.get(colors, x + 4), 
//                                            style = get_style(1)))
//         array.set(ulinefill, x + 4, linefill.new(array.get(uplines, x + 5), array.get(uplines, x == 0 ? 0 : x + 4), color.new(array.get(colors, x + 4), transp)))
//         if showlabels
//             xlocc = line_get_bar_index(array.get(uplines, x + 5), l_bar_index, yloc11, 1)
//             array.set(labels, x + 5, label.new(x = xlocc, y = yloc11, text = str.tostring(array.get(divs, x)) + "/1", textcolor = array.get(colors, x + 4), style = label.style_none))

// // draw fan lines from highest      
// if h_bar_index > 0 and h_bar_index < bar_index
//     var downlines = array.new_line(9, na)
//     var labels = array.new_label(9, na)
//     var dlinefill = array.new_linefill(8, na)
//     remove_old_lll(downlines, labels, dlinefill)
    
//     // draw 1/1 line, show its label and keep its y level
//     array.set(downlines, 0, line.new(x1 = h_bar_index, y1 = hghest, x2 = h_bar_index + 1, y2 = hghest - middle, extend = extend.right, color = array.get(colors, 8), style = get_style(2)))
//     xloc = h_bar_index + labelloc
//     yloc11 = line.get_price(array.get(downlines, 0), xloc)
//     if showlabels
//         array.set(labels, 0, label.new(x = xloc, y = yloc11, text = "1/1", textcolor = array.get(colors, 8), style = label.style_none))
    
//     // draw other fan lines, labels, linefills
//     for x = 0 to 3
//         array.set(downlines, x + 1, line.new(x1 = h_bar_index, y1 = hghest, x2 = bar_index, y2 = hghest - (hghest - line.get_price(array.get(downlines, 0), bar_index)) / array.get(divs,x), 
//                                              extend = extend.right, 
//                                              color = array.get(colors, x + 4), 
//                                              style = get_style(2)))
//         array.set(dlinefill, x, linefill.new(array.get(downlines, x + 1), array.get(downlines, x), color.new(array.get(colors, x + 4), transp)))
//         if showlabels
//             yloc = line.get_price(array.get(downlines, x + 1), xloc)
//             array.set(labels, x + 1, label.new(x = xloc, y = yloc, text = str.tostring(array.get(divs, x)) + "/1", textcolor = array.get(colors, x + 4), style = label.style_none))
            
//         array.set(downlines, x + 5, line.new(x1 = h_bar_index, y1 = hghest, x2 = h_bar_index + 1, y2 = hghest - middle * array.get(divs,x), 
//                                              extend = extend.right, 
//                                              color = array.get(colors, x), 
//                                              style = get_style(2)))
//         array.set(dlinefill, x + 4, linefill.new(array.get(downlines, x + 5), array.get(downlines, x == 0 ? 0 : x + 4), color.new(array.get(colors, x), transp)))
//         if showlabels
//             xlocc = line_get_bar_index(array.get(downlines, x + 5), h_bar_index, yloc11, -1)
//             array.set(labels, x + 5, label.new(x = xlocc, y = yloc11, text = "1/" + str.tostring(array.get(divs, x)), textcolor = array.get(colors, x), style = label.style_none))



// //@version=5

// indicator  ("Educational: lines, linefill, labels & boxes"           , max_lines_count=200, overlay=true)

// selection  = input.string    ('Linefill'    , options=['Linefill'            ])
// options    = input.string    ('extend lines', options=['extend lines', 'none'])

// // –––––––––––––––––––––[ Fetch previous Weekly high/low ]–––––––––––––––––––––
// prevHigh_W = request.security(syminfo.tickerid, 'W', nz(high[1]), barmerge.gaps_off, barmerge.lookahead_on)
// prevLow_W  = request.security(syminfo.tickerid, 'W', nz(low [1]), barmerge.gaps_off, barmerge.lookahead_on)

// // –––––––––––––––––––––[         Create array's         ]–––––––––––––––––––––
// var linefill[] lnF = array.new <linefill> ()
// var int     [] dir = array.new <  int   > ()

// // –––––––––––––––––––––[      Add 1 linefill.new()      ]–––––––––––––––––––––
// if barstate.isfirst //or timeframe.change('W')
//     line1 = line.new(bar_index, prevHigh_W, bar_index +1, prevHigh_W, color= color.new(color.silver, 50) )
//     line2 = line.new(bar_index, prevLow_W , bar_index +1, prevLow_W , color= color.new(color.silver, 50) )
//     array.unshift   (lnF      ,                   linefill.new(line1, line2, color.new(color.blue  , 75)))
//     array.unshift   (dir      ,                                    0                                       )

// // –––––––––––––––––––––[      If broken, change color,                      
// //                             otherwise,   make lines
// //                             1     bar_index  longer   ]–––––––––––––––––––––
// getDir       = array.get(dir, 0)
// if getDir == 0
//     getLineF = array.get(lnF, 0)
//     getLine1 = linefill.get_line1(getLineF)
//     getLine2 = linefill.get_line2(getLineF)
//     // if close >  top  line  -> change color -> lime  ,  set dir to   1
//     if close > line.get_price    (getLine1, bar_index  )
//         linefill.set_color       (getLineF, color.new(color.lime, 75))
//         array.set                (dir     ,      0 ,  1)
//     else
//     // if close < bottom line -> change color -> red   ,  set dir to  -1
//         if close < line.get_price(getLine2, bar_index  )
//             linefill.set_color   (getLineF, color.new(#FF0000   , 75))
//             array.set            (dir     ,      0 , -1)
//     //
//     // notice the 'difference' and 'simularity'  between 'extend lines' & 'none'
//     if options == 'extend lines'   
//         line.set_x2              (getLine1, bar_index  )
//         line.set_x2              (getLine2, bar_index  )

// plot(   array.size(linefill.all), display = display.status_line)



//@version=5
indicator("Channel", overlay = true)

LEN_LEFT = 15
LEN_RIGHT = 5
pH = ta.pivothigh(LEN_LEFT, LEN_RIGHT)
pL = ta.pivotlow(LEN_LEFT, LEN_RIGHT)

// Bar indices of pivot points
pH_x1 = ta.valuewhen(pH, bar_index, 1) - LEN_RIGHT
pH_x2 = ta.valuewhen(pH, bar_index, 0) - LEN_RIGHT
pL_x1 = ta.valuewhen(pL, bar_index, 1) - LEN_RIGHT
pL_x2 = ta.valuewhen(pL, bar_index, 0) - LEN_RIGHT
// Price values of pivot points
pH_y1 = ta.valuewhen(pH, pH, 1)
pH_y2 = ta.valuewhen(pH, pH, 0)
pL_y1 = ta.valuewhen(pL, pL, 1)
pL_y2 = ta.valuewhen(pL, pL, 0)

if barstate.islastconfirmedhistory
    // Lines
    lH = line.new(pH_x1, pH_y1, pH_x2, pH_y2, extend = extend.right)
    lL = line.new(pL_x1, pL_y1, pL_x2, pL_y2, extend = extend.right)
    // Fill
    fillColor = switch
        pH_y2 > pH_y1 and pL_y2 > pL_y1 => color.green
        pH_y2 < pH_y1 and pL_y2 < pL_y1 => color.red
        => color.silver
    linefill.new(lH, lL, color.new(fillColor, 90))